services:
  mongo:
    container_name: callover-db
    image: mongo:7.0
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: callover-redis
    image: redis:8.6
    ports:
      - '6380:6380'

volumes:
  mongo-data:
